### ISSUE TITLE
Can't serialize some type of strings

### ISSUE THREAD

**Issue by TeMPOraL** [wlbr/cl-marshal#6] opened 2015-08-15 12:16 UTC
``` lisp
CL-USER> (ms:marshal "TeMPOraL")
(:PCODE 1 (:SIMPLE-STRING 1 "TeMPOraL"))
```

vs.

``` lisp
CL-USER> (ms:marshal "TeMPOraL")
; Evaluation aborted on #<SIMPLE-TYPE-ERROR expected-type: (AND VECTOR (SATISFIES ARRAY-HAS-FILL-POINTER-P)) datum: "TeMPOraL">.
```

The difference? After inspecting, first one:

```
#<(SIMPLE-ARRAY CHARACTER (8)) {1003E37E9F}>
--------------------
Dimensions: (8)
Element type: CHARACTER
Total size: 8
Adjustable: NIL
Fill pointer: NIL
```

Second one:

```
#<(VECTOR CHARACTER 8) {1002E6800F}>
--------------------
Dimensions: (8)
Element type: CHARACTER
Total size: 8
Adjustable: T
Fill pointer: NIL
```

(The first one I typed into the REPL, the second one is a string created somewhere in my program which I need to serialize.)

SBCL 1.2.10 Linux 3.16.0-34-generic X86-64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

**Comment by wlbr** [comment] 2015-08-15 22:34
Sorry, can't reproduce.
How do you create this special character vector?

**Comment by wlbr** [comment] 2015-12-01 09:53
Just some tests:

    (require 'marshal)
    (ms:marshal "TeMPOraL")

    (defparameter sstring "TeMPOraL")
    (defparameter bstring (make-array 8 :fill-pointer 8 :adjustable t :element-type 'character :initial-contents '(#\T #\e #\M #\P #\O #\r #\a #\L)))
    (defparameter nstring  (vector #\T #\e #\M #\P #\O #\r #\a #\L))

    (describe sstring)  ; --> simple-string 
    (describe bstring)  ; --> base-string in ccl, string in sbcl
    (describe nstring)  ; --> not a string, but a simple-vector

    (describe (ms:unmarshal (ms:marshal sstring)))
    (describe (ms:unmarshal (ms:marshal bstring)))
    (describe (ms:unmarshal (ms:marshal nstring)))

**Comment by wlbr** [comment] 2017-01-11 17:13
Hi,

thanks for the fix! I merged the pull request. I hope that you don't mind, that I slightly modified your solution a bit after the merge. So it does not rely a handler-case on the error-type, but simply checks, if a fill-pointer exists.

I've seen a number of fixes from you lately. Are you interested in getting write access to the repository (in case I fiddle out how to do that in Github)?

Thanks a lot!
Michael

**Closed by wlbr** 2017-01-11 17:13 UTC

**Comment by cage2** [comment] 2017-01-11 18:47
On Wed, Jan 11, 2017 at 09:13:20AM -0800, Michael Wolber wrote:
> Hi,

Hello!

> thanks for the fix!

You are welcome! :)

>I  merged the  pull  request. I  hope  that you  don't  mind, that  I
> slightly modified your solution a bit after the merge. So it does not
> rely  a handler-case  on  the  error-type, but  simply  checks, if  a
> fill-pointer exists.

Not a problem. In fact i think your solution is much more elegant than
mine.  I did  not even  know that  'array-has-fill-pointer-p' function
exists!  :)

>  I've seen a number of fixes  from you lately. Are you interested in
> getting write access to the repository  (in case I fiddle out how to
> do that in Github)?

Of  course yes!  :) I  am actually  using this  library in  one of  my
project and i would like to take care of it a little bit! :)

>
> Thanks a lot!

Thanks to you too!  :)
Bye.
C.
