### ISSUE TITLE
Can't serialize a CONS

### ISSUE THREAD

**Issue by chebert** [wlbr/cl-marshal#5] opened 2015-06-15 23:25 UTC
```
(marshal:marshal (cons 3 4))
```

Signals an error that 4 isn't a list.

SBCL: 1.2.6
cl-marshal-20150302-git
quicklisp 2015-04-07

**Comment by wlbr** [comment] 2016-12-27 15:01
It seems that quicklisp is not using the latest version of cl-marshal. If I use the trunk, then I cannot reproduce the error. I seem to have fixed the error some years ago.

I'll try to find out how to update the quicklisp distro.

**Comment by wlbr** [comment] 2016-12-28 11:55
Fixed with 2624335faff01a68611c07627b4b663bec82a711
Cudos to 'cage2' for the fix.

**Closed by wlbr** 2016-12-28 11:55 UTC
